language: php

php:
    - 7.1
    - 7.2
    - 7.3
    #- 7.4 @todo: not available yet on Travis

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - composer update

script: ./vendor/bin/phpunit
