services:
    _defaults:
        autoconfigure: true
        autowire: true

    SylvainDeloux\SymfonyQuickwins\:
        resource: '../src'

    SylvainDeloux\SymfonyQuickwins\Storage\TmpFile:
        autowire: false
